spring:
  datasource:
      url: jdbc:mysql://localhost/test?useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
#    default-property-inclusion: non_empty
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8010